# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blog Adventure on PHP and it's ecosystem
email: oxomichael@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  PHP, Development, Tools and a whole lot of thing
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://oxomichael.github.io/" # the base hostname & protocol for your site
twitter_username: oxomichael
github_username:  oxomichael

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Piwik
piwik:
 base_url: apps.mstash.net/piwik
 site_id: 2
